<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cloud.folium.adapt</groupId>
    <artifactId>adapt</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>pom</packaging>
    <modules>
        <module>ads-collector</module>
        <module>cmn-http</module>
        <module>common</module>
        <module>cmn-aps-client</module>
        <module>cmn-privacy</module>
        <module>cmn-exceptions</module>
        <module>cmn-cloudwatch-metrics</module>
        <module>http-client-async</module>
        <module>ats-client</module>
        <module>cmn-errors</module>
        <module>cmn-policies-cache</module>
        <module>policy</module>
        <module>cmn-redis</module>
        <module>cmn-test</module>
        <module>cmn-test-integration</module>
        <module>cmn-adstats</module>
        <module>_coverage-report</module>
        <module>data-filter-stats-aggregation</module>
        <module>cmn-bidder-adapter</module>
        <module>hb-configuration</module>
        <module>certificate-ads-manager</module>
        <module>bidder-client</module>
        <module>bidder-adapter</module>
        <module>cmn-stats</module>
        <module>hb-domain</module>
        <!--detekt module must be the last in the list-->
        <module>_detekt</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>

        <code.coverage.project.folder>${basedir}/../</code.coverage.project.folder>
        <code.coverage.overall.data.folder>${basedir}/target/</code.coverage.overall.data.folder>
        <itCoverageAgent></itCoverageAgent>

        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <kotlin.version>1.9.25</kotlin.version>
        <kotlin.coroutines.version>1.6.2</kotlin.coroutines.version>
        <spring.version>3.4.5</spring.version>
        <spring.cloud-version>2024.0.1</spring.cloud-version>
        <jacoco.maven.plugin.version>0.8.11</jacoco.maven.plugin.version>
        <logback.version>1.5.13</logback.version>
        <aws.sdk1.version>1.12.782</aws.sdk1.version>
        <aws.sdk2.version>2.20.126</aws.sdk2.version>

        <!--Common Modules-->

        <!--adapt-common-->
        <share.adapt.cmn.adstats.delivery>4.0.0</share.adapt.cmn.adstats.delivery>
        <configuration.data.model.version>4.2.9-CERT-SNAPSHOT</configuration.data.model.version>
        <configuration.service.api.version>4.3.0-CERT-SNAPSHOT</configuration.service.api.version>
        <ads.template.executor.version>4.0.0</ads.template.executor.version>
        <share.adapt.common.impression.counter.version>4.0.0</share.adapt.common.impression.counter.version>
        <share.adapt.signature.version>4.0.0</share.adapt.signature.version>

        <!--logger-->
        <shared.logger.version>2.5.1</shared.logger.version>

        <!--bidder-request-constructor-->
        <share.bidder.request.constructor.version>3.15.0</share.bidder.request.constructor.version>

        <!--ad-response-parser-->
        <share.ad.response.parser.version>2.8.0</share.ad.response.parser.version>

        <!--fw-url-processing-->
        <share.fw.url.processing.version>2.1.0</share.fw.url.processing.version>

        <!--async-http-client-->
        <share.async.http.client.version>2.2.0</share.async.http.client.version>

        <junitplatform.version>1.11.0</junitplatform.version>
        <jackson.version>2.15.2</jackson.version>
        <slf4j.version>2.0.6</slf4j.version>
        <msgpack.version>0.9.3</msgpack.version>
        <ipaddress.verion>5.3.3</ipaddress.verion>
        <mock.server.version>5.15.0</mock.server.version>
        <httpmime.version>4.5.13</httpmime.version>
        <commons.collections4.version>4.4</commons.collections4.version>

        <timestamp>${maven.build.timestamp}</timestamp>
        <maven.build.timestamp.format>yyyy-MM-dd HH:mm:ss</maven.build.timestamp.format>

        <!--Skip test phase-->
        <skip.tests.unit>false</skip.tests.unit>
        <!--Skip integration-test phase-->
        <skip.tests.integration>false</skip.tests.integration>
        <!--Skip tests & integration-tests compiling (-Dmaven.test.skip=true)-->
    </properties>

    <profiles>
        <profile>
            <id>skip.tests</id>
            <activation>
                <property>
                    <name>skipTests</name>
                    <value>true</value>
                </property>
            </activation>
            <properties>
                <!--Skip test phase-->
                <skip.tests.unit>true</skip.tests.unit>
                <!--Skip integration-test phase-->
                <skip.tests.integration>true</skip.tests.integration>
                <!--Skip tests & integration-tests compiling (-Dmaven.test.skip=true)-->
            </properties>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-jdk8</artifactId>
            <version>${kotlin.coroutines.version}</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>ads-collector</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-http</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>common</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-exceptions</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-cloudwatch-metrics</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-aps-client</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-privacy</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-redis</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>http-client-async</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-errors</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-policies-cache</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>policy</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-test</artifactId>
                <scope>test</scope>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-test-integration</artifactId>
                <version>1.0-SNAPSHOT</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-adstats</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>data-filter-stats-aggregation</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>ats-client</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-bidder-adapter</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>hb-configuration</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>certificate-ads-manager</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>bidder-client</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>bidder-adapter</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>cmn-stats</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.adapt</groupId>
                <artifactId>hb-domain</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers</artifactId>
                <version>1.18.0</version>
            </dependency>

            <!--Shared modules-->
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>logger</artifactId>
                <version>${shared.logger.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>signature</artifactId>
                <version>${share.adapt.signature.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>configuration-data-model</artifactId>
                <version>${configuration.data.model.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>ad-response-parser</artifactId>
                <version>${share.ad.response.parser.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>configuration-service-api</artifactId>
                <version>${configuration.service.api.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>cmn-adstats-delivery</artifactId>
                <version>${share.adapt.cmn.adstats.delivery}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>ads-template-executor</artifactId>
                <version>${ads.template.executor.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>async-http-client</artifactId>
                <version>${share.async.http.client.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>bidder-request-constructor</artifactId>
                <version>${share.bidder.request.constructor.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>csid-params-extractor</artifactId>
                <version>${share.fw.url.processing.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>cmn-impression-counter</artifactId>
                <version>${share.adapt.common.impression.counter.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-simple</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>cloud.folium.share</groupId>
                <artifactId>fw-parser</artifactId>
                <version>${share.fw.url.processing.version}</version>
            </dependency>

            <!--External modules-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${spring.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.14.0</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>${logback.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${aws.sdk2.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.lettuce</groupId>
                <artifactId>lettuce-core</artifactId>
                <version>6.1.8.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>s3</artifactId>
                <version>${aws.sdk2.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>lambda</artifactId>
                <version>${aws.sdk2.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>dynamodb-enhanced</artifactId>
                <version>${aws.sdk2.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>kinesis</artifactId>
                <version>${aws.sdk2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.asynchttpclient</groupId>
                <artifactId>async-http-client</artifactId>
                <version>3.0.1</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.spek</groupId>
                <artifactId>spek-api</artifactId>
                <version>1.1.5</version>
            </dependency>
            <dependency>
                <groupId>io.kotest</groupId>
                <artifactId>kotest-runner-junit5-jvm</artifactId>
                <version>5.9.1</version>
            </dependency>
            <dependency>
                <groupId>io.kotest</groupId>
                <artifactId>kotest-assertions-json-jvm</artifactId>
                <version>5.9.1</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.spek</groupId>
                <artifactId>spek-junit-platform-engine</artifactId>
                <version>1.1.5</version>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-inline</artifactId>
                <version>4.4.0</version>
            </dependency>
            <dependency>
                <groupId>org.mockito.kotlin</groupId>
                <artifactId>mockito-kotlin</artifactId>
                <version>4.1.0</version>
            </dependency>
            <dependency>
                <groupId>cglib</groupId>
                <artifactId>cglib-nodep</artifactId>
                <version>3.3.0</version>
            </dependency>
            <dependency>
                <groupId>org.objenesis</groupId>
                <artifactId>objenesis</artifactId>
                <version>2.1</version>
            </dependency>
            <dependency>
                <groupId>xmlunit</groupId>
                <artifactId>xmlunit</artifactId>
                <version>1.6</version>
            </dependency>
            <dependency>
                <groupId>org.xmlunit</groupId>
                <artifactId>xmlunit-matchers</artifactId>
                <version>2.3.0</version>
            </dependency>
            <dependency>
                <groupId>org.junit.platform</groupId>
                <artifactId>junit-platform-engine</artifactId>
                <version>${junitplatform.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.platform</groupId>
                <artifactId>junit-platform-commons</artifactId>
                <version>${junitplatform.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.platform</groupId>
                <artifactId>junit-platform-launcher</artifactId>
                <version>${junitplatform.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>5.11.0</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>5.11.0</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-params</artifactId>
                <version>5.11.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>1.10.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commons.collections4.version}</version>
            </dependency>
            <dependency>
                <groupId>net.andreinc</groupId>
                <artifactId>mockneat</artifactId>
                <version>0.4.8</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>2.10.1</version>
            </dependency>
            <dependency>
                <groupId>com.github.seancfoley</groupId>
                <artifactId>ipaddress</artifactId>
                <version>${ipaddress.verion}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.module</groupId>
                <artifactId>jackson-module-kotlin</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlinx</groupId>
                <artifactId>kotlinx-coroutines-jdk8</artifactId>
                <version>${kotlin.coroutines.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>4.4.0</version>
            </dependency>
            <dependency>
                <groupId>com.jayway.jsonpath</groupId>
                <artifactId>json-path-assert</artifactId>
                <version>2.2.0</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.msgpack</groupId>
                <artifactId>jackson-dataformat-msgpack</artifactId>
                <version>${msgpack.version}</version>
            </dependency>
            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>2.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro</artifactId>
                <version>1.11.4</version>
            </dependency>
            <dependency>
                <groupId>org.xerial.snappy</groupId>
                <artifactId>snappy-java</artifactId>
                <version>1.1.10.5</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>33.0.0-jre</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-http2</artifactId>
                <version>4.1.100.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec</artifactId>
                <version>4.1.100.Final</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib</artifactId>
                <version>${kotlin.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib-common</artifactId>
                <version>${kotlin.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-reflect</artifactId>
                <version>${kotlin.version}</version>
            </dependency>
            <dependency>
                <groupId>org.json</groupId>
                <artifactId>json</artifactId>
                <version>20231013</version>
            </dependency>
            <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>2.3.1</version>
            </dependency>

            <dependency>
                <groupId>redis.clients</groupId>
                <artifactId>jedis</artifactId>
                <version>3.1.0</version>
            </dependency>

            <dependency>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-client-java</artifactId>
                <version>${mock.server.version}</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>mockserver</artifactId>
                <version>1.21.3</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>localstack</artifactId>
                <version>1.19.0</version>
            </dependency>
            <dependency>
                <groupId>org.freemarker</groupId>
                <artifactId>freemarker</artifactId>
                <version>2.3.32</version>
            </dependency>
            <dependency>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-runtime</artifactId>
                <version>4.9.3</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpmime</artifactId>
                <version>${httpmime.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>${project.basedir}/src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>kotlin-maven-plugin</artifactId>
                <groupId>org.jetbrains.kotlin</groupId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                                <sourceDir>${project.basedir}/src/test-integration/kotlin</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <jvmTarget>21</jvmTarget>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <includes>
                        <include>**/*Test.*</include>
                        <include>**/*Spec.*</include>
                    </includes>
                    <excludes>
                        <exclude>**/*IntSpec.*</exclude>
                        <exclude>**/*IntTest.*</exclude>
                        <exclude>**/*IntegrationTest.*</exclude>
                    </excludes>
                    <!--These properties must not be overwritten, otherwise the JaCoCo agent cannot be attached -->
                    <argLine>@{argLine} -Xmx1024m</argLine>
                    <reuseForks>true</reuseForks>
                    <environmentVariables>
                        <LOG_LEVEL>info</LOG_LEVEL>
                        <TESTCONTAINERS_RYUK_CONTAINER_IMAGE>
                            public.ecr.aws/u9z3s7u4/adapt:ryuk.0.5.1
                        </TESTCONTAINERS_RYUK_CONTAINER_IMAGE>
                    </environmentVariables>
                    <systemProperties>
                        <property>
                            <name>org.slf4j.simpleLogger.defaultLogLevel</name>
                            <value>warn</value>
                        </property>
                    </systemProperties>
                    <reportsDirectory>${project.build.directory}/surefire-reports/unit</reportsDirectory>
                    <reportNameSuffix>Unit</reportNameSuffix>
                    <systemPropertyVariables>
                        <kotest.framework.classpath.scanning.autoscan.disable>true
                        </kotest.framework.classpath.scanning.autoscan.disable>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <phase>integration-test</phase>
                        <configuration>
                            <includes>
                                <include>**/*IntSpec.*</include>
                                <include>**/*IntTest.*</include>
                            </includes>
                            <excludes>none</excludes>
                            <reportsDirectory>${project.build.directory}/surefire-reports/integration</reportsDirectory>
                            <reportNameSuffix>Integration</reportNameSuffix>
                            <argLine>@{argLine} ${itCoverageAgent} -Xmx1024m</argLine>
                            <additionalClasspathElements>
                                ${project.basedir}/src/test-integration/resources
                            </additionalClasspathElements>
                            <environmentVariables>
                                <AWS_ACCESS_KEY_ID>somekey</AWS_ACCESS_KEY_ID> <!--Temp fix, need smth better-->
                                <AWS_SECRET_ACCESS_KEY>somesecret</AWS_SECRET_ACCESS_KEY>
                            </environmentVariables>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>add-test-sources</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <!-- Configures the source directory of our integration tests -->
                            <sources>
                                <source>src/test-integration/kotlin</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-resource</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>add-test-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>src/test-integration/resources</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <!-- prepare agent before integration tests -->
                    <execution>
                        <id>default-report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <phase>pre-integration-test</phase>
                        <configuration>
                            <propertyName>itCoverageAgent</propertyName>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <excludes>
                        <exclude>**/*Config.*</exclude>
                        <exclude>cloud/folium/detekt/**/*</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <!-- todo  enhanced lifecycle, see if it  helps to speed up build-->
            <!--<plugin>
                <groupId>io.takari.maven.plugins</groupId>
                <artifactId>takari-lifecycle-plugin</artifactId>
                <extensions>true</extensions>
            </plugin>-->
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.4.1</version>
                    <configuration>
                        <createDependencyReducedPom>false</createDependencyReducedPom>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>shade</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <pluginRepositories>
        <pluginRepository>
            <id>sling-jcenter-cache</id>
            <name>Sling JCenter Cache Repository</name>
            <url>https://dishtechnology.pe.jfrog.io/artifactory/jcenter-cache/</url>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>mavenCentral</id>
            <url>https://repo1.maven.org/maven2/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>sling-jcenter-cache</id>
            <url>https://dishtechnology.pe.jfrog.io/artifactory/jcenter-virtual/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>adapt-snapshots</id>
            <url>https://dishtechnology.pe.jfrog.io/artifactory/adapt-mvn-local/</url>
            <snapshots>
                <updatePolicy>interval:5</updatePolicy>
                <checksumPolicy>ignore</checksumPolicy>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
        <repository>
            <id>adapt-releases</id>
            <url>https://dishtechnology.pe.jfrog.io/artifactory/adapt-mvn-local/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>
</project>
